In [1]:
import pandas as pd

In [2]:
import numpy as np

In [7]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

### *Creating arrays*

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7 ,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[4] = 10

In [13]:
a

array([ 1,  2,  3,  5, 10, 12])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### *Multi-Dementional Arrays*

In [18]:
np.zeros((5,2))
# 5 rows, 2 cols

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [21]:
n[0, 2]

np.int64(3)

In [22]:
n[2]

array([7, 8, 9])

In [24]:
n[ : , 1]
# : 放在「row」的位置 → 意思是「所有列都要」

array([2, 5, 8])

### *Randomly Generated Arrays*

In [31]:
# seed(() fixed now
# np.random.rand() 0-1
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [34]:
# seed(() fixed now
np.random.seed(3)
100*np.random.rand(5, 2)

array([[55.07979026, 70.81478226],
       [29.09047389, 51.08276052],
       [89.29469543, 89.62930889],
       [12.55853105, 20.72428781],
       [ 5.14672033, 44.08098437]])

In [36]:
np.random.seed(5)
np.random.randint(low=0, high=100, size=(5,2))

array([[99, 78],
       [61, 16],
       [73,  8],
       [62, 27],
       [30, 80]])

### *Element-wise operations*

In [40]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
# only np can do not panada
(10 + (a * 2)) ** 2

array([100, 144, 196, 256, 324])

### *Comparison Operations*

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a >= 2 

array([False, False,  True,  True,  True])

In [53]:
b = np.arange(7, 42, 7)
b

array([ 7, 14, 21, 28, 35])

In [55]:
b[b > a]

array([ 7, 14, 21, 28, 35])

### *Summarizing Operation*

In [56]:
a.max()

np.int64(4)

In [57]:
a.mean()

np.float64(2.0)

## *Linear Algebra*

### *Vector Operations*

In [59]:
u = np.array([2, 4, 5, 6])

In [60]:
u * 2

array([ 4,  8, 10, 12])

In [61]:
v = np.array([1, 0, 0, 2])

In [62]:
u + v

array([3, 4, 5, 8])